package com.example.core.domain.usecase

import com.example.core.data.Resource
import com.example.core.domain.repository.IRepository
import com.example.core.domain.usecase.model.*
import kotlinx.coroutines.flow.Flow

class Interactor(private val repository: IRepository): IUseCase {
    override fun login(email: String, password: String): Flow<Resource<LoginDomain>> = repository.login(email, password)
    override fun register(name: String, email: String, password: String): Flow<Resource<UserDataDomain>> = repository.register(name, email, password)
    override fun logout(bearer: String): Flow<Resource<String>> = repository.logout(bearer)
    override fun addData(bearer: String, avgHeartRate: Int, stepChanges: Int, step: Int, label: String?, createdAt: String?): Flow<Resource<Boolean>> = repository.addData(bearer, avgHeartRate, stepChanges,step, label.toString(), createdAt.toString())
    override fun findData(bearer: String, avgHeartRate: Int, avgStep: Int): Flow<Resource<List<String>>> = repository.findData(bearer, avgHeartRate, avgStep)
    override fun getProfile(bearer: String): Flow<Resource<UserDataDomain>> = repository.getProfile(bearer)
    override fun getUserMonitoringData(bearer: String): Flow<Resource<List<MonitoringDataDomain>>> = repository.getUserMonitoringData(bearer)
    override fun getUserMonitoringDataByDate(bearer: String, start: String, end: String): Flow<Resource<List<MonitoringDataDomain>>> = repository.getUserMonitoringDataByDate(bearer, start, end)
    override fun getAverageData(bearer: String): Flow<Resource<AverageDomain>> = repository.getAverageData(bearer)
    override fun deleteData(bearer: String, id: Int): Flow<Resource<String>> = repository.deleteData(bearer, id)
    override fun updateMonitoringData(bearer: String, avgHeartRate: Int, avgStep: Int, label: String): Flow<Resource<MonitoringDataDomain>> = repository.updateMonitoringData(bearer, avgHeartRate, avgStep, label)
    override fun updateUser(bearer: String, name: String, email: String, dob: String, gender: Int, height: Int, weight: Int): Flow<Resource<UserDataDomain>> = repository.updateUser(bearer, name, email, dob, gender, height, weight)
    override fun changePassword(bearer: String, old: String, new: String, confirmation: String): Flow<Resource<String>> = repository.changePassword(bearer, old, new, confirmation)
    override fun sendNotification(bearer: String, status: Int): Flow<Resource<String>> = repository.sendNotification(bearer, status)
    override fun addContact(bearer: String, contact: Int): Flow<Resource<String>> = repository.addContact(bearer, contact)
    override fun getContacts(bearer: String): Flow<Resource<List<UserDataDomain>>> = repository.getContacts(bearer)
    override fun getLimit(bearer: String): Flow<Resource<LimitDomain>> = repository.getLimit(bearer)
    override fun search(bearer: String, param: String): Flow<Resource<List<UserDataDomain>>> = repository.search(bearer, param)
    override fun deleteContact(bearer: String, contact: Int): Flow<Resource<String>> = repository.deleteContact(bearer, contact)
    override fun setBearer(bearer: String) = repository.setBearer(bearer)
    override fun getBearer(): Flow<String?> = repository.getBearer()
    override fun setLoginState(state: Boolean) = repository.setLoginState(state)
    override fun getLoginState(): Flow<Boolean> = repository.getLoginState()
    override fun setUserId(id: Int) = repository.setUserId(id)
    override fun getUserId(): Flow<Int> = repository.getUserId()
    override fun setLatestLoginDate(date: String) = repository.setLatestLoginDate(date)
    override fun getLatestLoginDate(): Flow<String?> = repository.getLatestLoginDate()
    override fun setMonitoringPeriod(period: Int) = repository.setMonitoringPeriod(period)
    override fun getMonitoringPeriod(): Flow<Int> = repository.getMonitoringPeriod()
    override fun setMinHRLimit(min: Int) = repository.setMinHRLimit(min)
    override fun getMinHRLimit(): Flow<Int> = repository.getMinHRLimit()
    override fun setMaxHRLimit(max: Int) = repository.setMaxHRLimit(max)
    override fun getMaxHRLimit(): Flow<Int> = repository.getMaxHRLimit()
    override fun setAnomalyDetectedTimes(times: Int) = repository.setAnomalyDetectedTimes(times)
    override fun getAnomalyDetectedTimes(): Flow<Int> = repository.getAnomalyDetectedTimes()
    override fun setLatestAnomalyDate(date: String) = repository.setLatestAnomalyDate(date)
    override fun getLatestAnomalyDate(): Flow<String?> = repository.getLatestAnomalyDate()
    override fun setBackgroundMonitoringState(state: Boolean) = repository.setBackgroundMonitoringState(state)
    override fun getBackgroundMonitoringState(): Flow<Boolean> = repository.getBackgroundMonitoringState()
    override fun getMonitoringDataList(): List<MonitoringDataDomain> = repository.getMonitoringDataList()
    override fun deleteMonitoringDataById(id: Int) = repository.deleteMonitoringDataById(id)
    override fun deleteMonitoringDataByDate(date: String) = repository.deleteMonitoringDataByDate(date)
    override fun insertMonitoringData(monitoringData: MonitoringDataDomain) = repository.insertMonitoringData(monitoringData)
}